use std::{
    fs::File,
    io::{self, BufRead, BufReader},
    net::Ipv4Addr,
};

use crate::conf::MAXNS;

/* example on /etc/resolv.conf */
// # DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN
//
// nameserver no.no.no.no
// nameserver no:no:no::no
// search *.*.net

pub fn get_dns_v4() -> Result<Vec<Ipv4Addr>, io::Error> {
    let file = File::open("/etc/resolv.conf")?;
    let mut reader = BufReader::new(file);
    let mut line_buf = String::new();
    let mut nameservers = Vec::with_capacity(MAXNS);
    loop {
        line_buf.clear();
        let bytes_read = reader.read_line(&mut line_buf)?;
        if bytes_read == 0 {
            break;
        }
        let line = line_buf.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("nameserver")
            && let Some(ip_token) = rest.split_whitespace().next()
            && let Ok(ip) = ip_token.parse::<Ipv4Addr>()
        {
            if nameservers.len() < MAXNS {
                nameservers.push(ip);
            } else {
                break;
            }
        }
    }
    Ok(nameservers)
}
